version: "3.9"

services:
  docker1:
    build: .
    container_name: docker1
    networks:
      network10:
        ipv4_address: 192.168.10.10
    command: ["bash", "-c", "while true; do sleep 3600; done"]

  dockerbridge:
    build: .
    container_name: dockerbridge
    networks:
      network10:
        ipv4_address: 192.168.10.11
      network20:
        ipv4_address: 192.168.20.11
    sysctls:
      net.ipv4.ip_forward: 1
    command: ["bash", "-c", "while true; do sleep 3600; done"]

  docker2:
    build: .
    container_name: docker2
    networks:
      network20:
        ipv4_address: 192.168.20.10
    command: ["bash", "-c", "while true; do sleep 3600; done"]

networks:
  network10:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  network20:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
